/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: '#7C3AED', // violet-600
                    50: '#F5F3FF',
                    100: '#EDE9FE',
                    200: '#DDD6FE',
                    300: '#C4B5FD',
                    400: '#A78BFA',
                    500: '#8B5CF6',
                    600: '#7C3AED',
                    700: '#6D28D9',
                    800: '#5B21B6',
                    900: '#4C1D95',
                },
                accent: {
                    DEFAULT: '#A3E635', // lime-400
                    50: '#F7FEE7',
                    100: '#ECFCCB',
                    200: '#D9F99D',
                    300: '#BEF264',
                    400: '#A3E635',
                    500: '#84CC16',
                    600: '#65A30D',
                    700: '#4D7C0F',
                    800: '#3F6212',
                    900: '#365314',
                },
                surface: {
                    light: '#FFFFFF',
                    dark: '#000000',
                },
                background: {
                    light: '#FFFBEB', // amber-50
                    dark: '#000000',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                mono: ['Courier New', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
            },
            boxShadow: {
                'brutal': '4px 4px 0px 0px rgba(0,0,0,1)',
                'brutal-sm': '2px 2px 0px 0px rgba(0,0,0,1)',
                'brutal-lg': '8px 8px 0px 0px rgba(0,0,0,1)',
            },
            animation: {
                'mascot-blink': 'blink 150ms ease-in-out',
                'mascot-breathe': 'breathe 2s ease-in-out infinite',
                'mascot-tilt': 'tilt 300ms ease-out',
                'mascot-tremble': 'tremble 100ms linear infinite',
                'mascot-pop': 'pop 200ms ease-out',
                'mascot-recoil': 'recoil 200ms ease-out',
                'mascot-sigh': 'sigh 300ms ease-in',
                'mascot-shake': 'shake 200ms ease-out',
                'mascot-wink': 'wink 300ms ease-out',
                'mascot-glint': 'glint 400ms ease-out',
                'stress-shake': 'stressShake 150ms ease-in-out infinite',
                'breathe-heavy': 'breatheHeavy 3s ease-in-out infinite',
                'heart-attack': 'heartAttack 300ms ease-in-out infinite',
                'bounce-light': 'bounceLight 600ms ease-in-out',
                'jitter': 'jitter 80ms ease-in-out infinite',
                'stress-pulse': 'stressPulse 500ms ease-in-out infinite',
                'hard-shake': 'hardShake 120ms ease-in-out infinite',
                'pulse-slow': 'pulseSlow 4s ease-in-out infinite',
                'bounce-short': 'bounceShort 400ms ease-out',
            },
            keyframes: {
                blink: {
                    '0%, 100%': { transform: 'scaleY(1)' },
                    '50%': { transform: 'scaleY(0.1)' },
                },
                breathe: {
                    '0%, 100%': { transform: 'scale(1)' },
                    '50%': { transform: 'scale(1.02)' },
                },
                tilt: {
                    '0%, 100%': { transform: 'rotate(0deg)' },
                    '50%': { transform: 'rotate(-2deg)' },
                },
                tremble: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-1px)' },
                },
                pop: {
                    '0%': { transform: 'scale(1)' },
                    '50%': { transform: 'scale(1.06)' },
                    '100%': { transform: 'scale(1)' },
                },
                recoil: {
                    '0%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-4px)' },
                    '100%': { transform: 'translateY(0)' },
                },
                sigh: {
                    '0%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(2px)' },
                    '100%': { transform: 'translateY(0)' },
                },
                shake: {
                    '0%, 100%': { transform: 'translateX(0)' },
                    '25%': { transform: 'translateX(-2px)' },
                    '75%': { transform: 'translateX(2px)' },
                },
                wink: {
                    '0%, 100%': { transform: 'scaleY(1)' },
                    '50%': { transform: 'scaleY(0.1)' },
                },
                glint: {
                    '0%': { opacity: '0', transform: 'translateX(-10px)' },
                    '50%': { opacity: '1' },
                    '100%': { opacity: '0', transform: 'translateX(10px)' },
                },
                stressShake: {
                    '0%, 100%': { transform: 'translateX(0)' },
                    '10%': { transform: 'translateX(-3px) rotate(-1deg)' },
                    '20%': { transform: 'translateX(3px) rotate(1deg)' },
                    '30%': { transform: 'translateX(-3px) rotate(-1deg)' },
                    '40%': { transform: 'translateX(3px) rotate(1deg)' },
                    '50%': { transform: 'translateX(-2px) rotate(-0.5deg)' },
                    '60%': { transform: 'translateX(2px) rotate(0.5deg)' },
                    '70%': { transform: 'translateX(-2px) rotate(-0.5deg)' },
                    '80%': { transform: 'translateX(2px) rotate(0.5deg)' },
                    '90%': { transform: 'translateX(-1px)' },
                },
                breatheHeavy: {
                    '0%, 100%': { transform: 'scale(1)' },
                    '50%': { transform: 'scale(1.08)' },
                },
                heartAttack: {
                    '0%, 100%': { transform: 'scale(1) rotate(0deg)' },
                    '25%': { transform: 'scale(1.15) rotate(2deg)' },
                    '50%': { transform: 'scale(0.95) rotate(-2deg)' },
                    '75%': { transform: 'scale(1.1) rotate(1deg)' },
                },
                bounceLight: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-8px)' },
                },
                jitter: {
                    '0%': { transform: 'translate(0, 0)' },
                    '10%': { transform: 'translate(-2px, -1px)' },
                    '20%': { transform: 'translate(2px, 1px)' },
                    '30%': { transform: 'translate(-1px, 2px)' },
                    '40%': { transform: 'translate(1px, -2px)' },
                    '50%': { transform: 'translate(-2px, 1px)' },
                    '60%': { transform: 'translate(2px, -1px)' },
                    '70%': { transform: 'translate(-1px, -2px)' },
                    '80%': { transform: 'translate(1px, 2px)' },
                    '90%': { transform: 'translate(-2px, -1px)' },
                    '100%': { transform: 'translate(0, 0)' },
                },
                stressPulse: {
                    '0%, 100%': { transform: 'scale(1)' },
                    '25%': { transform: 'scale(1.08)' },
                    '50%': { transform: 'scale(0.95)' },
                    '75%': { transform: 'scale(1.05)' },
                },
                hardShake: {
                    '0%, 100%': { transform: 'translateX(0) rotate(0deg)' },
                    '10%': { transform: 'translateX(-5px) rotate(-3deg)' },
                    '20%': { transform: 'translateX(5px) rotate(3deg)' },
                    '30%': { transform: 'translateX(-5px) rotate(-3deg)' },
                    '40%': { transform: 'translateX(5px) rotate(3deg)' },
                    '50%': { transform: 'translateX(-4px) rotate(-2deg)' },
                    '60%': { transform: 'translateX(4px) rotate(2deg)' },
                    '70%': { transform: 'translateX(-3px) rotate(-1deg)' },
                    '80%': { transform: 'translateX(3px) rotate(1deg)' },
                    '90%': { transform: 'translateX(-2px) rotate(-0.5deg)' },
                },
                pulseSlow: {
                    '0%, 100%': { transform: 'scale(1)', opacity: '1' },
                    '50%': { transform: 'scale(1.03)', opacity: '0.95' },
                },
                bounceShort: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '40%': { transform: 'translateY(-12px)' },
                    '60%': { transform: 'translateY(-6px)' },
                },
            },
        },
    },
    plugins: [],
};
